GET http://localhost:8080/api/companies/1/workers
Accept: application/json

###
GET http://localhost:8080/api/companies/1
Accept: application/json

###
GET http://localhost:8080/api/companies
Accept: application/json

###



