POST http://localhost:8080/api/companies/1/workers
Content-Type: application/json

{
  "name": "New worker",
  "age": 99
}

###
PUT http://localhost:8080/api/companies/1/workers/7
Content-Type: application/json

{
  "name": "Updated worker"
}

###
DELETE http://localhost:8080/api/companies/1/workers/7

###
GET http://localhost:8080/api/companies/1/workers/3
Accept: application/json

###

POST http://localhost:8080/api/companies
Content-Type: application/json

{
 "name": "New company2",
  "age": 99
}

###
PUT http://localhost:8080/api/companies/7
Content-Type: application/json

{
  "name": "Updated company"
}

###
DELETE http://localhost:8080/api/companies/1

###
GET http://localhost:8080/api/companies/1/workers
Accept: application/json

###
GET http://localhost:8080/api/companies/1
Accept: application/json

###
GET http://localhost:8080/api/companies
Accept: application/json

###
GET http://localhost:8082/api/workers/1
Accept: application/json

###


